steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'server/Dockerfile',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tare/tare-server:$COMMIT_SHA',
        './server'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tare/tare-server:$COMMIT_SHA'